### ISSUE TITLE
Using without num-traits.

### ISSUE THREAD

**Issue by xStrom** [mikedilger/float-cmp#25]
Previously with `0.6.0` it was possible to use `ApproxEq` without `num-traits` by importing like this:
```toml
[dependencies]
float-cmp = { version = "0.6.0", default-features = false }
```

However with `0.7.0` that no longer works:
```
error[E0599]: no method named `abs` found for type `f32` in the current scope
   --> /float-cmp-0.7.0/src/eq.rs:100:29
    |
100 |             ((self - other).abs() <= margin.epsilon) ||
    |                             ^^^ method not found in `f32`

error[E0599]: no method named `abs` found for type `f64` in the current scope
   -->/float-cmp-0.7.0/src/eq.rs:226:29
    |
226 |             ((self - other).abs() <= margin.epsilon) ||
    |                             ^^^ method not found in `f64`

error: aborting due to 2 previous errors
```

I'm guessing this is caused by #24. Possibly also related is [rust-lang#50145](https://github.com/rust-lang/rust/issues/50145).

**Comment by mikedilger** [comment]
Good point.

I just pushed a change so that if 'num-traits' is disabled it will pull in 'std'.  It needs one or the other.
If you are happy with that and want a point release, let me know.

EDIT: I force-push overwrote that change, check the 'feats' branch instead.

**Comment by mikedilger** [comment]
Actually I'm going to rework this further. The meaning of these features has become obscure.

'num-traits' feature enables the ratio module. That' not intuitive anymore.  I am thinking of creating a 'ratio' feature for that (which will pull in num-traits).

Then for people who prefer to avoid 'std', we can have a 'nostd' feature.  If 'nostd' is enabled, and 'ratio' is not enabled, then we can pull in 'libm' (which is what num-traits uses to get things like abs()).

If core::intrinsics wasn't a nightly experimental feature, I'd use that.

**Comment by mikedilger** [comment]
@aurelj @xStrom I've pushed a branch 'feats' and I'd like both of your feedback on whether or not this works for you and/or if you have suggestions to make it better.

First, a new feature named 'ratio' pulls in the 'ratio' module (rather than using the 'num-traits' to determine this).  It depends on num_traits.  'ratio' is on by default since it has always been in the past and we want the least amount of suprise.  That means 'std' is not necessary for people compiling with default features, so 'std' is also not included by default.

If you want to disable 'ratio', then you have to enable either 'std' or 'num-traits' in order to get functions like abs().  Your choice.

**Comment by xStrom** [comment]
I tested out the `feats` branch and it works well. There's a typo in the new `README.md` though: *ehter*.

**Comment by aurelj** [comment]
The `feats` branch works fine for me as well, for my various test cases, including some no_std target.

It looks good to me.

**Comment by mikedilger** [comment]
Thanks for the quick replies.

I've published this as 0.8, as changing features would be a breaking change.
